---
title: "Reproducible and Automated Research with R for Urbanists"
author: "Claudiu Forgaci & Barbara Vreede"
date: "October 10, 2022"
output:
  ioslides_presentation:
    highlight: pygments
    widescreen: yes
---

# Wrap-up

## The four dimensions of reproducibility

- Organisation: structure, formats, data
- Automation: scripting
- Documentation: literate programming
- Dissemination: publishing and archiving


## Topics we did not cover

> - **An in-depth introduction to R.** Consider joining one of our two-day [Data Carpentry workshops](https://www.tudelft.nl/en/library/research-data-management/r/training-events/training-for-researchers/data-carpentry-workshops) (open to researchers from TUD, EUR, ULeiden & UvA).
> - **Version control.** Consider joining one of our two-day [Software Carpentry workshops](https://www.tudelft.nl/library/research-data-management/r/training-evenementen/training-voor-onderzoekers/software-carpentry-workshops) (open to researchers from TUD, EUR, ULeiden & UvA).
> - **Reproducible environments**: 
>     - [Docker containers](https://the-turing-way.netlify.app/reproducible-research/renv/renv-containers.html) to reproduce the entire system used for the research; 
>     - [binder](https://the-turing-way.netlify.app/communication/binder/zero-to-binder.html) for building and sharing reproducible and interactive computational environments from online repositories;
>     - [renv](https://rstudio.github.io/renv/articles/renv.html) for R dependency management.
> - **R packaging** as an alternative way of making research reproducible. Wickham and Bryan's [R Packages](https://r-pkgs.org/) is a great book to learn about packaging (in general, beyond reproducibility).


## What's next (in Rbanism)?

> - **Join the Urbanism ReproHack on Friday 14 October, 13:00-17:00!** The ReproHack is a hands-on event in which participants will be applying the tools, skills, and knowledge gained in this workshop on published papers! Others are welcome too!

> - **Join the Reproducibility Challenge between 14 October - 14 November!** The Challenge will be open to the international urbanism research community.

> - **Stay tuned for the next round of events in spring 2023 on Scalable GIS!** - 1-day workshop + half-day hackathon + 1-month challenge.

> - **Drinks!** Thank you all for participating!